baseURL = 'https://mlashcorp.github.io/no_generals_problem/'
languageCode = 'en-us'
title = 'The No Generals Problem'
theme = 'PaperMod'

[params]
  author = "José Côrte-Real"
  description = "A blog about distributed systems."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/mlashcorp"
